# Pandas Dataframes

In [ ]:
# Series is a 1dimensional structure like ek table ka ek column is like a series 
# Dataframes is 2dimensional structure of data consisting of series and rows .
#Dataframe ke single row ya column ko bolte hai series

In [ ]:
#Creation of dataframe requires a 2D list if creating from list
#The list which is created below usme har row mainn is order se data bhara hai iq, marks,package_secured 

# https://drive.google.com/drive/folder... is link se dataset download karle aage jaake use honge (ony movues and ipl_matches hi use honge)
import numpy as np
import pandas as pd
student_data=[
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
    
]
pd.dataframe(student_data,columns=["iq","marks","package"])
#as you can see columns parameter main list of columns to be created pass karoge

In [ ]:
#Creating from a dictionary 
student_dict = {
    'name':['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}
#as you can see har key se ek list of data  associated hai since keys to column ka naam ban hi jayengi to unke  adar ki series ya data bhi dena hi hoga 

students = pd.DataFrame(student_dict) #yahan you can see since keys column ban jayegi to columns parameter dena nhi pada 
print(students)

students.set_index('name',inplace=True) #diresct student dataframe main change karega and jo  internally index allocate hue hai uski jagah name ko index bana dega  row based 
#inplace=True se direct original dataframe main change  hoga gar False hota ya nhi hota too alag dataframe banata usme changes karke wo return karta 
students

      name   iq  marks  package
0   nitish  100     80       10
1    ankit   90     70        7
2   rupesh  120    100       14
3  rishabh   80     50        2
4     amit    0      0        0
5   ankita    0      0        0
None

In [ ]:
fp1=r"C:\Users\Asus\Downloads\ipl-matches.csv"
#jitne ipl 2022 tak khele gaye unka dataset
fp2=r"C:\Users\Asus\Downloads\movies.csv"
#saari movies and unse related cheezon ka dataset

matches=pd.read_csv(fp1)
movies=pd.read_csv(fp2)

#shape btata hai kitne rows and columns in dataframes 

movies.shape
matches.shape

#dtypes batata hai columns ka datatypes
matches.dtypes

ID                   int64
City                   str
Date                   str
Season                 str
MatchNumber            str
Team1                  str
Team2                  str
Venue                  str
TossWinner             str
TossDecision           str
SuperOver              str
WinningTeam            str
WonBy                  str
Margin             float64
method                 str
Player_of_Match        str
Team1Players           str
Team2Players           str
Umpire1                str
Umpire2                str
dtype: object

In [15]:
#index batata hai index kahan se start hai kahan pe khatam kitne increment par 

print(matches.index,movies.index)

RangeIndex(start=0, stop=950, step=1) RangeIndex(start=0, stop=1629, step=1)

In [ ]:
#columns saare  ke saare jo hai wo ek Index object main daalke dedega (unka naam )
print(type(movies.columns),matches.columns,students.columns)

<class 'pandas.Index'> Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str') Index(['iq', 'marks', 'package'], dtype='str')

In [ ]:
#values saari ki saari values fetch karega and the 2D numpyarray main daalke dedega
# jahan ek row ke andar na puri row rahegi of  dataframe 

# values
students.values
matches.values

In [ ]:
#head and tail working just like series
movies.head() #top ki 5 movies series ki taarah isko bhi custom tareeke se use kar skte hai 

movies.head(16)
#same with tail

In [ ]:
#sample :-bias ke basis pe data select karna taaki koi slected and biased data na ho randomm ho 
movies.sample() #andar koi number specify karoge to utne random data dega nhii to ek hi dega

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
112,Bhavesh Joshi Superhero,tt6129302,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhavesh_Joshi_Su...,Bhavesh Joshi Superhero,Bhavesh Joshi Superhero,0,2018,154,Action|Drama,7.6,4928,Bhavesh Joshi Superhero is an action film abou...,The origin story of Bhavesh Joshi an Indian s...,This year| justice will have a new name.,Harshvardhan Kapoor|Priyanshu Painyuli|Ashish ...,2 nominations,1 June 2018 (USA)

In [22]:
#info high level info dega regarding your dataframe .Bahut tareeke ka info  ek saath dikhai dega 

movies.info()
#har column main kitni missinng values hai ye batayega kitni existing hai ye batayegga and then har column ka  datatype bhi batayega 

matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [24]:
#isnull check karega har column main ki missing values hai ya nhi boolean dataframe return karega and then isko bhi as a boolean mask use kar skte ho 
movies.isnull().sum()

#par sirf boolean dataframe ko dekh ke smajh nhi aayega ki kitni hai missing values  hai har column main fir ye kya  karega ki sum ka use karke sare columns ke true add karke batayega ki ek column main kitni missing values hai

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [ ]:
#duplicated batayega ki aapke dataframe main duplicated values hai ya nhi  kyunki duplicated data analysis kharab hi karta  hai 
movies.duplicated()
#  ye kuch aisa return dega ki row number hoga and uske aage true ya false hoga false meaning data duplicated nhi hai true meaning ki hai 

#Ab yeh jaana hai  ki total kitni rows duplicated hai toh sum() laga  do
movies.duplicated().sum()

students.duplicated().sum() #1 row duplicate huyi hai

np.int64(1)

In [23]:
# describe is used to give mathematical summary of arithmetic columns in dataframe 

movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [ ]:
#Dataframe ke column ka naam badalne ke liye .rename()
#Students main package ke badle lpa and marks ke badle percent hoga nam ]

students.rename(columns={"marks":"percentage","package":"lpa"}) #ye ek nya dtaframe banayega jisme n=marks column ka naam percentage and package column ka naam lpa hoga then usko return karega agar chahte  hoon ki original dataframe main changes ho to inplace parameter ki vale True set kardo 

#Also isme jo dictionary pass hogi na usme jo column change karne hai wo  as key pass honge adn unko jis naam se value se replace karna hai wo un keys ke samne aayengi 

# students.rename(columns={"marks":"percentage","package":"lpa"},inplace=True)

In [ ]:
#Mathmeatical Methods 

#movies dataframe pe sum lagane se har column ke upa r sum apply kiya
movies.sum() #logical nhi hai sabpe lagana toh kisi ek ya do pe lagoa necessary wala pe toh hi better hai 

students.sum()

#Abhi to column pe sum lag rha tha par chaho to axis parameter ki help se row wise bhi  kar skte ho 

students.sum(axis=1)

students.mean() #bhi har column ka mean nikalke de dega axis=1 use karlo row wise mean axis=0 is default behaviour 

students.min()
students.max()
students.median()
students.mode() #jo cheez sabse zyada baar aayegi column main
students.std()
students.var()
#ye saare methods jo series main the yahan pe bhi hai phark bas itna hai ki axis ka use karke row wise and column wise bhi nikal skte ho

   iq  marks  package
0   0      0        0

In [37]:
#Selecting columns froma dataframes 

#supposemovies dataframe main se sirf movie name ka column chahiye 

movies["title_x"]# single column hai to series kehlayega chaho  to type(movies["title_x"]) karke dekhlo

#multiple colums chahiye to fancy indexing kro 
movies[["title_x","year_of_release","actors"]]
#isko slicing of dataframe bhi bol skte hai kyunki ek part nikala hai 
#jis order main list mai  columns ke name pass kiye hai na usi order main dikhai denge 

matches[["Team1","Team2","WinningTeam"]]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

In [ ]:
#Selecting rows ya fetching rows 

student_dict1={
    "name":["Nitish","Ankit","Rupesh","Rishabh","Amit","Ankita"],
    "iq":[100,90,120,80,0,0],
    "marks":[80,70,100,50,0,0],
    "package":[10,7,14,2,0,0]

}
student=pd.DataFrame(student_dict1)
student.set_index("name",inplace=True)

#Functions used:iloc,loc
#iloc searches using index positions while loc searches using index labels
movies.iloc[0] #ek single row dega bhai and since slicing and fancy indexing allowed multiple bhi fetch kar sakte ho and also  ek row is a series
# [rows,colums] ke form main handle karta hai ye ] 

student.loc["Nitish"] #ye index ke label ke hisaab se fetch karega rows

#Multiple items ke  liye 
student.loc[["Nitish","Ankita","Ankit"]]

'tt8291224'

In [ ]:
#Selectinng both rows and columns :-
# mujhe sirf pehle 3 coulms ka data chahiye dfor  first 3 movies
movies.iloc[0:3,0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [ ]:
#Filtering a data frame 
matches

#jitne ipl hue hai har saal ke winner ka naam batao (find all winners )(season se pata chal jayega ki saal kounsa hai winning team se winner pata chal  jayega and then har saal ka winner chahiye yni final jeetne wala yni match nhumber se final  mil jayega)

#Sabse pehle ye nikalunga ki kounse kounse matches are final ?
mask=matches["MatchNumber"]=="Final"

new_df=matches[mask]
#ab mere pass ek aisi dataframe hai jiska har maych final hai ab inke winners chhaiy e and season

new_df[["Season","WinningTeam"]]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [64]:
#Out of all ipl matches kitne matches main super over hua hai ?
matches

#ab mereko woh saare matches chahiye jimne super over hua tha yni matches ka column but super over wala 

mask=matches["SuperOver"]=="Y"
new_df=matches[mask]
#ab mujhe ye jaana hai ki kitne matches hue hai therefore mujhe number of rows batana hai 
new_df.shape[0]

14

In [75]:
#csk ne kolkata  main kitne match jite ?
matches
mask=matches["WinningTeam"]=="Chennai Super Kings"
new_Df=matches[mask]
mask2=new_Df["City"]=="Kolkata"
new_df2=new_Df[mask2]
new_df2.shape[0]

#isko aur easily bhi kar skte the bitwise and se 
improved_mask=((matches["City"]=="Kolkata") & (matches["WinningTeam"]=="Chennai Super Kings"))
new_df3=matches[improved_mask].shape[0]
print(new_df3)

5

In [ ]:
#toss winner is match winner in percentage (matlab toss jitne par kitne baar aise hua ki toss winning team is match winning team)
matches
mask=((matches["TossWinner"])==(matches["WinningTeam"]) )
new_df=matches[mask] #isme wo saari teams hai jisne toss jitne par match jita ab mujhe nikalna hai ki iska percenntage kya hai agar nikalnna hota ki kitne baar hua hai 

#now to calculate percentage 
percentage=(new_df.shape[0]/matches.shape[0])*100
print(percentage)

51.473684210526315

In [ ]:
# movies with rating higher than 8 and votes>10000
movies
mask=((movies["imdb_rating"]>8) & (movies["imdb_votes"]>10000))
new_df=movies[mask]
#now new _df only has all data whose imdb_rating is>8 and imdb_votes >10000
#Now i have to calculate aise kitni movies hai
print(f" Number of movies with rating>8 and votes>10000 is:{new_df.shape[0]}")

 Number of movies with rating>8 and votes>10000 is:43

In [88]:
# Action movies with rating 7.5
movies

# now problem is ki genre main pure ek genre nhi hai multiple genres ka combination hai  jisme action bh aata hai toh pehle mujhe genres main jaake action ko nikalna padega then i will be able to compare 

#pehel main movies["genres"] karke genres column mainn chala gaya now i have that column jisne saari string values are present then main unko split karunga to split karne ke liye string main convert karna hoga  str ka use karke then split karunga   

# movies["genres"].str.split("|") 
#Ab shi movies split to hogyi  but then list hai to main apply function ka use karke custom logic lagaunga 

mask=movies["genres"].str.split("|").apply(lambda x:"Action" in x )
mask1=mask &(movies["imdb_rating"]>7.5)
new_df=movies[mask]
new_df

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)
13,Total Dhamaal,tt7639372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Total_Dhamaal,Total Dhamaal,Total Dhamaal,0,2019,130,Action|Adventure|Comedy,4.3,4817,Total Dhamaal is the third instalment in the D...,A group of people learn about a hidden treasur...,The Wildest Adventure Ever,Ajay Devgn|Madhuri Dixit|Anil Kapoor|Riteish D...,NaN,22 February 2019 (India)
14,Sonchiriya,tt8108200,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sonchiriya,Sonchiriya,Sonchiriya,0,2019,143,Action|Crime|Drama,7.5,2322,This is the story of a group of rebels in Cham...,Set in the Chambal valley the film follows th...,NaN,Sushant Singh Rajput|Bhumi Pednekar|Manoj Bajp...,NaN,1 March 2019 (India)
16,Mard Ko Dard Nahi Hota,tt8055888,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mard_Ko_Dard_Nah...,Mard Ko Dard Nahin Hota,Mard Ko Dard Nahin Hota,0,2018,134,Action|Comedy,7.4,3969,It is a story of a young boy Surya who has a r...,It is a story of a young boy Surya who has a r...,NaN,Abhimanyu Dasani|Radhika Madan|Prateek Parmar|...,2 wins & 2 nominations,22 March 2019 (USA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,Hadh: Life on the Edge of Death,tt0396044,NaN,https://en.wikipedia.org/wiki/Hadh:_Life_on_th...,Hadh: Life on the Edge of Death,Hadh: Life on the Edge of Death,0,2001,\N,Action|Crime|Drama,4.5,11,Abandoned by his biological mother nicknamed ...,Abandoned by his biological mother nicknamed ...,NaN,Somesh Agarwal|Shama Deshpande|Vikram Gokhale|...,NaN,NaN
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)
1608,One 2 Ka 4,tt0227194,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/One_2_Ka_4,One 2 Ka 4,One 2 Ka 4,0,2001,169,Action|Comedy|Crime,5.4,4484,Javed Abbas (Jackie Shroff) is a widowed polic...,When a cop's partner is killed in the line of ...,NaN,Shah Rukh Khan|Juhi Chawla|Jackie Shroff|Nirma...,NaN,30 March 2001 (India)
1617,Officer (2001 film),tt0265452,NaN,https://en.wikipedia.org/wiki/Officer_(2001_film),Officer,Officer,0,2001,\N,Action|Crime|Drama,5.3,97,SPU unit officer Sagar Chauhan is assigned wit...,SPU unit officer Sagar Chauhan is assigned wit...,NaN,Sunil Shetty|Raveena Tandon|Danny Denzongpa|,NaN,14 March 2001 (Kuwait)
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)

In [92]:
#Adding new Columns :-
#completely new columns 

movies["Country"]="India"
movies #Country naam ka column add hojayega and uski saari values ko india set kardenge 

#From existing ones 
# movies["lead_actor"]=movies["actors"].str.split("|").apply(lambda x:x[0])
#this will not worlk coz of  missing values 

new_df=movies.dropna()["actors"].str.split("|").apply(lambda x:x[0])
new_df

11             Ranveer Singh
34              Gavie Chahal
37        Ayushmann Khurrana
87         Sidharth Malhotra
96                Ajay Devgn
                ...
1600             Divya Dutta
1601               Anant Nag
1607             Anil Kapoor
1621    Priyanshu Chatterjee
1623          Karisma Kapoor
Name: actors, Length: 298, dtype: str

In [ ]:
#Important Dataframe functions 
import numpy as np
#astype :- given column ka datatype change karta hai 
matches.info()
#ID ka data int64 se int 32 main karte  hai 

matches["ID"].astype("int32")
#PErmanent change ke liye 
# matches["ID"]=matches["ID"].astype("int32") size bhi reduce hojayega

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

0      1312200
1      1312199
2      1312198
3      1312197
4      1304116
        ...
945     335986
946     335985
947     335984
948     335983
949     335982
Name: ID, Length: 950, dtype: int32

In [ ]:
#value_counts